name: Python pytest CI

on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run pytest with JUnit XML report
        run: |
          pytest --junitxml=reports/junit.xml

      - name: Show pytest results
        if: always()
        uses: pmeier/pytest-results-action@main
        with:
          path: reports/junit.xml
          summary: true
          display-options: fEX
          fail-on-empty: true
          title: Pytest Results
